// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj91Bq6-IguZpGpxvcS92IkzEMkXaMws0',
    appId: '1:960220809551:web:608021a14cbf4bed991d3a',
    messagingSenderId: '960220809551',
    projectId: 'itda-fcm-test',
    authDomain: 'itda-fcm-test.firebaseapp.com',
    storageBucket: 'itda-fcm-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMtI7C6H0CcLjS0Ca10pZHeWTR-e3DzJg',
    appId: '1:960220809551:android:226e25520ba2da5d991d3a',
    messagingSenderId: '960220809551',
    projectId: 'itda-fcm-test',
    storageBucket: 'itda-fcm-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwFNgunhoCi_6ESlC1NhjUNmkVXhrdLbE',
    appId: '1:960220809551:ios:05fdf55eb52348b3991d3a',
    messagingSenderId: '960220809551',
    projectId: 'itda-fcm-test',
    storageBucket: 'itda-fcm-test.firebasestorage.app',
    iosBundleId: 'com.example.preItda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwFNgunhoCi_6ESlC1NhjUNmkVXhrdLbE',
    appId: '1:960220809551:ios:05fdf55eb52348b3991d3a',
    messagingSenderId: '960220809551',
    projectId: 'itda-fcm-test',
    storageBucket: 'itda-fcm-test.firebasestorage.app',
    iosBundleId: 'com.example.preItda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj91Bq6-IguZpGpxvcS92IkzEMkXaMws0',
    appId: '1:960220809551:web:cacd08546862ff23991d3a',
    messagingSenderId: '960220809551',
    projectId: 'itda-fcm-test',
    authDomain: 'itda-fcm-test.firebaseapp.com',
    storageBucket: 'itda-fcm-test.firebasestorage.app',
  );
}
